# Official OraDBA Extensions Registry
# This file lists all official extensions whose documentation will be included
# in the main OraDBA documentation site.

extensions:
  - name: oradba_extension
    display_name: OraDBA Extension Template
    repo: oehrlis/oradba_extension
    docs_path: doc  # Path in extension repo containing markdown files
    description: Template and example for creating OraDBA extensions
    category: Development
    maintainer: Stefan Oehrli
    status: active
    
  - name: odb_datasafe
    display_name: OraDBA Data Safe Extension
    repo: oehrlis/odb_datasafe
    docs_path: doc
    description: Tools for managing Oracle Data Safe targets in OCI with simplified CLI and comprehensive logging
    category: Operations
    maintainer: Stefan Oehrli
    status: active
    
  - name: odb_autoupgrade
    display_name: OraDBA AutoUpgrade Extension
    repo: oehrlis/odb_autoupgrade
    docs_path: doc
    description: Oracle AutoUpgrade wrapper scripts with ready-to-use configs for database upgrades
    category: Operations
    maintainer: Stefan Oehrli
    status: active
    
  - name: odb_extras
    display_name: OraDBA Extras Extension
    repo: oehrlis/odb_extras
    docs_path: doc
    description: Additional Oracle DBA utilities and helper scripts
    category: Operations
    maintainer: Stefan Oehrli
    status: active
    
  # Add more extensions here as they are approved:
  # - name: oradba_monitoring
  #   display_name: OraDBA Monitoring Extension
  #   repo: oehrlis/oradba_monitoring
  #   docs_path: doc
  #   description: Monitoring scripts and dashboards for Oracle databases
  #   category: Operations
  #   maintainer: Your Name
  #   status: active
