name: Bug Report
description: Create a report to help us improve
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below with as much detail as possible.

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Run command '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Oracle Linux 8
        - Oracle Linux 9
        - Red Hat Enterprise Linux 8
        - Red Hat Enterprise Linux 9
        - Ubuntu 20.04
        - Ubuntu 22.04
        - Ubuntu 24.04
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Other (please specify in Additional Context)
    validations:
      required: true

  - type: input
    id: shell
    attributes:
      label: Shell
      description: What shell are you using?
      placeholder: e.g., bash 5.1, zsh
    validations:
      required: true

  - type: input
    id: oradba-version
    attributes:
      label: oradba Version
      description: What version of oradba are you using?
      placeholder: e.g., 0.2.0
    validations:
      required: true

  - type: input
    id: oracle-version
    attributes:
      label: Oracle Database Version
      description: What version of Oracle Database are you using?
      placeholder: e.g., 19.20.0.0, 21.13.0.0
    validations:
      required: false

  - type: textarea
    id: error-messages
    attributes:
      label: Error Messages
      description: Paste any error messages or logs here
      render: shell
      placeholder: Paste error messages here...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, logs, etc.)
      placeholder: Any additional information...
    validations:
      required: false

  - type: textarea
    id: possible-solution
    attributes:
      label: Possible Solution
      description: If you have suggestions on how to fix the bug, please describe them here
      placeholder: Suggestions for fixing the bug...
    validations:
      required: false
