name: Feature Request
description: Suggest an idea for this project
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below with as much detail as possible.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see.
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: Describe the problem this feature would solve.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: A clear and concise description of what you want to happen.
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternative-solutions
    attributes:
      label: Alternative Solutions
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: Describe alternative approaches...
    validations:
      required: false

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: What environment would this feature be used in?
      options:
        - Production
        - Development
        - Lab/Testing
        - All environments
    validations:
      required: true

  - type: dropdown
    id: frequency
    attributes:
      label: Usage Frequency
      description: How often would you use this feature?
      options:
        - Daily
        - Weekly
        - Monthly
        - Occasionally
        - One-time
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: Impact Level
      description: What impact would this feature have on your workflow?
      options:
        - High - Critical for my workflow
        - Medium - Significantly improves workflow
        - Low - Nice to have
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: Provide examples of how this feature would be used
      render: shell
      placeholder: |
        # Example command or usage
        source oraenv.sh --new-feature FREE
    validations:
      required: false

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: List the benefits of implementing this feature
      placeholder: |
        - Benefit 1
        - Benefit 2
        - Benefit 3
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references about the feature request here
      placeholder: Any additional information...
    validations:
      required: false
