name: Task
description: Create a task for project maintenance or improvement
title: "[TASK] "
labels: ["task"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for creating a task! Please fill out the form below to help organize project work.

  - type: textarea
    id: task-description
    attributes:
      label: Task Description
      description: A clear and concise description of the task to be completed.
      placeholder: Describe the task...
    validations:
      required: true

  - type: textarea
    id: objective
    attributes:
      label: Objective
      description: What is the goal or expected outcome of this task?
      placeholder: What should be achieved?
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component does this task relate to?
      options:
        - Environment setup (oradba.env))
        - Library functions (oradba_db_functions.sh, oradba_common.sh)
        - Installer (build/installation)
        - Tests (BATS test suite)
        - Documentation
        - CI/CD (GitHub Actions)
        - Configuration files
        - Shell scripts
        - SQL scripts
        - RMAN scripts
        - Other (specify in Implementation Notes)
    validations:
      required: true

  - type: dropdown
    id: task-type
    attributes:
      label: Task Type
      description: What type of task is this?
      options:
        - Refactoring
        - Documentation
        - Testing
        - Maintenance
        - Migration
        - Enhancement
        - Configuration
        - Build/Release
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: What is the priority of this task?
      options:
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: List the specific requirements or deliverables
      placeholder: |
        - [ ] Requirement 1
        - [ ] Requirement 2
        - [ ] Requirement 3
    validations:
      required: true

  - type: textarea
    id: implementation-notes
    attributes:
      label: Implementation Notes
      description: Provide any technical details or implementation guidance
      render: shell
      placeholder: |
        # Example code or approach
        function new_feature() {
            # Implementation
        }
    validations:
      required: false

  - type: textarea
    id: testing-criteria
    attributes:
      label: Testing Criteria
      description: Describe how this task should be tested
      placeholder: |
        - [ ] Test case 1
        - [ ] Test case 2
        - [ ] Test case 3
    validations:
      required: false

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Define what "done" means for this task
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: false

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: List any dependencies or related tasks/issues
      placeholder: |
        - Related to #123
        - Depends on #456
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or information about the task
      placeholder: Any additional information...
    validations:
      required: false
