# markdownlint configuration for the extension template
MD013:
  line_length: 120
  code_blocks: false
  tables: false
  headings: true

MD024:
  siblings_only: true

MD033:
  allowed_elements:
    - br
    - details
    - summary
    - kbd

MD041: false
