-- -----------------------------------------------------------------------------
-- OraDBA - Oracle Database Infrastructure and Security, 5630 Muri, Switzerland
-- -----------------------------------------------------------------------------
-- Name......: sec_whoami_show.sql
-- Author....: Stefan Oehrli (oes) stefan.oehrli@oradba.ch
-- Editor....: Stefan Oehrli
-- Date......: 2026.01.13
-- Revision..: 0.18.3
-- Purpose...: Alias for spsec_usrinf.sql
-- Usage.....: n/a
-- Notes.....: n/a
-- Reference.: 
-- Reference.: https://github.com/oehrlis/oradba
-- License...: Apache License Version 2.0, January 2004 as shown
--             at http://www.apache.org/licenses/
-- -----------------------------------------------------------------------------
@spsec_usrinf.sql
-- EOF -------------------------------------------------------------------------