-- -----------------------------------------------------------------------------
-- OraDBA - Oracle Database Infrastructure and Security, 5630 Muri, Switzerland
-- -----------------------------------------------------------------------------
-- Name.......: tde.sql
-- Author.....: Stefan Oehrli (oes) stefan.oehrli@oradba.ch
-- Editor.....: Stefan Oehrli
-- Date.......: 2026.01.01
-- Revision...: 0.9.5
-- Purpose....: Alias for tde_info_dba.sql
-- Notes......: Simple wrapper script for TDE status information
-- Usage......: @tde
-- Reference..: https://github.com/oehrlis/oradba
-- License....: Apache License Version 2.0, January 2004 as shown
--              at http://www.apache.org/licenses/
-- -----------------------------------------------------------------------------
@tde_info_dba.sql
-- EOF -------------------------------------------------------------------------
