-- ------------------------------------------------------------------------------
-- OraDBA - Oracle Database Infrastructure and Security, 5630 Muri, Switzerland
-- ------------------------------------------------------------------------------
-- Name.......: tdeops.sql
-- Author.....: Stefan Oehrli (oes) stefan.oehrli@oradba.ch
-- Editor.....: Stefan Oehrli
-- Date.......: 2025.12.19
-- Revision...: 0.8.0
-- Purpose....: Alias for tde_ops_show_dba.sql
-- Notes......: Simple wrapper script for TDE operations
-- Usage......: @tdeops
-- Reference..: https://github.com/oehrlis/oradba
-- License....: Apache License Version 2.0, January 2004 as shown
--              at http://www.apache.org/licenses/
-- ------------------------------------------------------------------------------
@tde_ops_show_dba.sql
-- EOF -------------------------------------------------------------------------
