-- -----------------------------------------------------------------------------
-- OraDBA - Oracle Database Infrastructure and Security, 5630 Muri, Switzerland
-- -----------------------------------------------------------------------------
-- Name......: verify_user_password_no.sql
-- Author....: Stefan Oehrli (oes) stefan.oehrli@oradba.ch
-- Editor....: Stefan Oehrli
-- Date......: 2026.01.13
-- Revision..: 0.18.3
-- Purpose...: Wrapper script to check if a user in sys.user$  
--              has a weak password. Passwords will not be displayed
-- Usage.....: @verify_user_password_no
-- Notes.....: 
-- Reference.: requires execute on dbms_crypto
-- License...: Apache License Version 2.0, January 2004 as shown
--             at http://www.apache.org/licenses/
----------------------------------------------------------------------------
--  Modified..:
--  see git revision history for more information on changes/updates
----------------------------------------------------------------------------
@verify_passwords.sql FALSE &1 60
-- EOF ---------------------------------------------------------------------