-- -----------------------------------------------------------------------------
-- OraDBA - Oracle Database Infrastructure and Security, 5630 Muri, Switzerland
-- -----------------------------------------------------------------------------
-- Name......: verify_alluser_passwords_no.sql
-- Author....: Stefan Oehrli (oes) stefan.oehrli@oradba.ch
-- Editor....: Stefan Oehrli
-- Date......: 2026.02.11
-- Revision..: 0.21.0
-- Purpose...: Wrapper script to check if any user in sys.user$  
--              has a weak password. Passwords will not be displayed
-- Usage.....:  @verify_alluser_passwords_no
-- Notes.....: 
-- Reference.: verify_passwords.sql has to be in the SQLPATH
-- License...: Apache License Version 2.0, January 2004 as shown
--             at http://www.apache.org/licenses/
----------------------------------------------------------------------------
--  Modified..:
--  see git revision history for more information on changes/updates
----------------------------------------------------------------------------
@verify_passwords.sql FALSE % 60
-- EOF ---------------------------------------------------------------------