--------------------------------------------------------------------------------
--  OraDBA - Oracle Database Infrastructure and Security, 5630 Muri, Switzerland
--------------------------------------------------------------------------------
--  Name......: whoami.sql
--  Author....: Stefan Oehrli (oes) stefan.oehrli@oradba.ch
--  Editor....: Stefan Oehrli
--  Date......: 2024.08.21
--  Revision..:  
--  Purpose...: Alias for spsec_usrinf.sql
--  Usage.....: n/a
--  Notes.....: n/a
--  Reference.: 
--  License...: Apache License Version 2.0, January 2004 as shown
--              at http://www.apache.org/licenses/
--------------------------------------------------------------------------------
@spsec_usrinf.sql
-- EOF -------------------------------------------------------------------------